In [1]:
import numpy as np 

In [8]:
x = [1,2,3,4,5]
y = np.array(x)
print(y)
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print(type(x))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [7]:
l =[]
for i in range(1,5):
    int_1 = int(input("enter no.: "))
    l.append(int_1)

print(np.array(l))

enter no.:  5
enter no.:  6
enter no.:  6
enter no.:  7


[5 6 6 7]


In [13]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3
