## Numpy library import 

In [2]:
import numpy as np 

# create Array and convert list in to array

In [2]:
x = [1,2,3,4,5]
y = np.array(x)
print(y)
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print(type(x))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


# take input elements in array and conwert list in to array 

In [3]:
l =[]
for i in range(1,5):
    a = int(input("Enter a number: "))
    l.append(a)

print(np.array(l))

[1 2 3 4]


# check the dimensions of the array using "ndim" function

In [4]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3


# create multidimentional array using "ndmin = dimention of the array"

In [5]:
arr = np.array([1,2,3,5], ndmin = 10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 5]]]]]]]]]]
10


# create numpy array using Numpy Functions
1. Array filled with 0's
2. Array filled with 1's
3. Create an empty array
4. An array with a range of elements 
5. Array diagonal element filled with 1's
6. Create an arrat eith values that are spaced linearly in a specified interval 

## Zeros

In [6]:
import numpy as np
# create numpy array using Numpy Functions
# 1. Array filled with 0's
a = np.zeros(4)
print(a)
print("\n")
b = np.zeros((5,2))
print(b)

[0. 0. 0. 0.]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Ones

In [7]:
arr1 = np.ones(3)
print(arr1)
print("\n")

arr2 = np.ones((4,2,5))
print(arr2)
print(arr2.ndim)

[1. 1. 1.]


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
3


# Empty Array

In [8]:
ar_em = np.empty(4)
print(ar_em)
print("\n")
ar_em2 = np.empty((3,4))
print(ar_em2)

[0. 0. 0. 0.]


[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
 [2.0e-323 2.5e-323 3.0e-323 3.5e-323]]


# Range

In [9]:
range_arr = np.arange(10)
print(range_arr)
print("\n")
range_arr2 = np.arange(1,20,3)
print(range_arr2)


[0 1 2 3 4 5 6 7 8 9]


[ 1  4  7 10 13 16 19]


## diagonal filled with 1

In [10]:
arr_dia = np.eye(3)
print(arr_dia)
print("\n")

arr_dia2 = np.eye(3,3)
print(arr_dia2)
print("\n")

arr_dia2 = np.eye(3,3, k = 1)
print(arr_dia2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# Give a proper space "Linspace"

In [11]:
arr_lin = np.linspace(1,10, num = 5) # num = 5 means number of elements in a array
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]


## Create array using random numbers 

# Random 

Rand()

In [12]:
var = np.random.rand(5)
print(var)
print("\n")
var2 = np.random.rand(3,4)
print(var2)

[0.29524966 0.54792886 0.76952857 0.32349863 0.42832132]


[[0.79482907 0.86947509 0.49506223 0.3522175 ]
 [0.26377476 0.59107048 0.10534872 0.37617422]
 [0.457053   0.29121166 0.291351   0.18233836]]


Randn()

In [13]:
var3 = np.random.randn(4)
print(var3)
print("\n")
var4 = np.random.randn(3,4) 
print(var4)

[ 0.97176798  0.17305593  1.20626846 -1.27503899]


[[ 0.19463069 -1.01578834 -2.01255091  0.36199833]
 [ 0.59561864  1.71585839  2.00243936  0.39567373]
 [ 0.59140687  1.19715769  0.35142472  1.18769224]]


Ranf()

In [14]:
var_4 = np.random.ranf(4)
print(var_4)
print("\n")
var_5 = np.random.ranf(8)
print(var_5)

[0.38619153 0.40139008 0.79269291 0.59886582]


[0.07932483 0.81818579 0.54604975 0.65566662 0.56655372 0.29065514
 0.35584486 0.11953909]


randint()

In [15]:
var6 = np.random.randint(4,10,4)
print(var6)
print("\n")
var7 = np.random.randint(1,100, (3,4,5))
print(var7)
print(var7.ndim)

[5 9 5 9]


[[[63 25 55 59 62]
  [81 91 45 65 86]
  [55 80 22 35 97]
  [23 35 82  2 83]]

 [[92 12 57 58 49]
  [12 90 16 30  8]
  [70 22 53 60 57]
  [55 76 17 97 54]]

 [[26 47 29 47 11]
  [16 83 24 76 98]
  [98 12 18 24 39]
  [70 45 25 85 81]]]
3


# Datatype in Numpy Arrays

Check data type

In [16]:
var = np.array([5,6,78,9])
print(var.dtype)
print("\n")
var1 = np.array([5,6,78,9])
print(var1.dtype)
print("\n")
var2 = np.array([5,6,78,9,"a","b","c",7,8,9])
print(var2.dtype)

int64


int64


<U21


Store data from int64 to int8

In [17]:
x = np.array([5,6,7,8], dtype = np.int8)
print(x.dtype)

int8


Convert in to another after changing the dtype value 

In [18]:
x = np.array([5,6,7,8], dtype = "f")
print(x.dtype)

float32


convert the data type of an array in to another datatype using dtype function 

In [19]:
x = np.array([5,6,7,8])
new = np.float32(x)
new_1 = np.int8(new)
print(x.dtype)
print(new.dtype)
print(new_1.dtype)

int64
float32
int8


Directly change the datatype 

Astype function is used to convert the data type of an array into another data type.

In [20]:
new_1 = new.astype(float)
print(new_1)
print(new_1.dtype)

[5. 6. 7. 8.]
float64


# Arthmetic operations in numpy arrays
1. Add
2. Subs
3. mul
4. div
5. mod
6. power
7. reciprocal

In [21]:
a = np.array([1,2,3,4,5])
var_add = a+3
print(var_add)

[4 5 6 7 8]


In [22]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
var = a + b
print(var)

[ 6  8 10 12 14]


Inplace of a+b we use functions to perform arthimetic operations

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.add(a,b)
print(c)
# like that we have substract, multiply, divide, sqrt, etc functions in numpy


[ 6  8 10 12 14]


# Arithmetic Functions

In [24]:
A = np.array([1,4,5,6,73,5,6,7,7,8,8])
print("max",np.max(A))
print("min",np.min(A))   

max 73
min 1


In [25]:
print("maximmum with index value.:",np.max(A),np.argmax(A))
print("minimmum with index value.:",np.min(A),np.argmin(A))

maximmum with index value.: 73 4
minimmum with index value.: 1 0


In [26]:
B = np.array([[1,2,3,4],[5,6,78,7]])
print(B)
print("max:", np.max(B, axis = 0))  # column wise maximum
print("max:", np.max(B, axis = 1))  # row wise maximum

[[ 1  2  3  4]
 [ 5  6 78  7]]
max: [ 5  6 78  7]
max: [ 4 78]


# Shape and Reshaping of an array

Shape

In [28]:
c = np.array([[13,45,13,12],[14,42,115,6234]])
print(c)
print("shape", np.shape(c))

[[  13   45   13   12]
 [  14   42  115 6234]]
shape (2, 4)


Reshape

In [48]:
d = np.array([[13,45,13,12],[14,42,115,6234]])
print(d)
print("dimensions", d.ndim)
e = d.reshape(4,2)
print(e)
print("shape",np.shape(e))

[[  13   45   13   12]
 [  14   42  115 6234]]
dimensions 2
[[  13   45]
 [  13   12]
 [  14   42]
 [ 115 6234]]
shape (4, 2)


# Broad casting

esme ye hota hai ki 3cro1 aur 1 cross 3 ke array se bo dono arrays se highest value nikalega aur add karega esse broad casting ki error handle karta ha 

In [53]:
x = np.array([[1],[22],[45]])
y = np.array([1,2,3])
print(np.add(x,y))
print(x.shape)
print(y.shape)


[[ 2  3  4]
 [23 24 25]
 [46 47 48]]
(3, 1)
(3,)


# Slicing and Indexing

## Indexing

In [12]:
sli = np.array([1,2,3,4,5,6,7,8,9])
print(sli[0])
print(sli[0:5])
print(sli[-1:-5:-1])
print(sli[::-1])
print(sli)

1
[1 2 3 4 5]
[9 8 7 6]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [ ]:
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d)
print(two_d[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[[4 5 6]]


In [29]:
three_d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
print(three_d)
print(three_d[2,1,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
25


## Slicing

In [32]:
var = np.array([3,4,5,5,6,6,7,8,8,99])
print(var)

print(var[1:5])  #slicing
print(var[::2])  #slicing with step size
print(var[::-1]) #reversing the array
print(var[::])

[ 3  4  5  5  6  6  7  8  8 99]
[4 5 5 6]
[3 5 6 7 8]
[99  8  8  7  6  6  5  5  4  3]
[ 3  4  5  5  6  6  7  8  8 99]


In [46]:
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d)
print(two_d[0,0])
print(two_d[1,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[5]


# Join and Split the array

## join
joining means putting content of two or more arrays in a single array

In [47]:
j = np.array([1,2,3,4,5])
k = np.array([6,7,8,9,10])
ar = np.concatenate((j,k))
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
l = np.array([[1,2,3,4,5],[34,5,6,77,44]])
m = np.array([[6,7,8,9,10],[22,3,44,52,6]])
ar1 = np.concatenate((l,m))
print(ar1)

[[ 1  2  3  4  5]
 [34  5  6 77 44]
 [ 6  7  8  9 10]
 [22  3 44 52  6]]


In [49]:
l = np.array([[1,2,3,4,5],[34,5,6,77,44]])
m = np.array([[6,7,8,9,10],[22,3,44,52,6]])
ar1 = np.concatenate((l,m),axis = 1)
print(ar1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [34  5  6 77 44 22  3 44 52  6]]


In [51]:
l = np.array([[1,2,3,4,5],[34,5,6,77,44]])
m = np.array([[6,7,8,9,10],[22,3,44,52,6]])
ar3 = np.concatenate((l,m),axis = 0)
print(ar3)

[[ 1  2  3  4  5]
 [34  5  6 77 44]
 [ 6  7  8  9 10]
 [22  3 44 52  6]]


In [ ]:
j = np.array([1,2,3,4,5])
k = np.array([6,7,8,9,10])
ar = np.stack((j,k),axis=1)
print(ar)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [58]:
j = np.array([1,2,3,4,5])
k = np.array([6,7,8,9,10])
ar = np.hstack((j,k))# rows
ar1 = np.vstack((j,k))# columns
ar2 = np.dstack((j,k))# height
print(ar)
print(ar1)
print(ar2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


## Split
splitting breaks one array in to multiple.

In [61]:
spt = np.array([1,2,3,4,5,6,7,8,9])
print(spt)
arr = np.array_split(spt,3)
print(arr)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [64]:
sptt = np.array([[1,2,3,4,5,6,7,8,9],[33,4,5,6,7,8,9,10,11]])
arr1 = np.array_split(sptt,2,axis=1)
print(arr1)

[array([[ 1,  2,  3,  4,  5],
       [33,  4,  5,  6,  7]]), array([[ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])]


# Array functions

## Search

In [ ]:
s = np.array([86,767,86,65,86,23,86,45,67])
n = np.where(s==86)

print(n)

(array([0, 2, 4, 6]),)


## Search Sorted 


In [67]:
SS = np.array([1,2,3,4,6,7])
p = np.searchsorted(SS,5)
print(p)

4


In [71]:
SS = np.array([1,2,3,4,5,8,9,22,33,45])
p = np.searchsorted(SS,24,side='right')
print(p)

8


## sort

In [72]:
so = np.array([66,3,45,11,666,444,5,6,0])
sn = np.sort(so)
print(sn)

[  0   3   5   6  11  45  66 444 666]


## filter

In [73]:
so = np.array([66,3,45,11,666,444,5,6,0])
f = [True,False,True,False,True,False,True,False,True]
new_so = so[f]
print( new_so)

[ 66  45 666   5   0]


## Suffle

In [82]:
var = np.array([5,6,78,9])
np.random.shuffle(var)
print(var)

[ 6  5  9 78]


## Unique

In [86]:
un = np.array([11,22,3,4,66,66,77,8,8,3,222,66])
np.unique(un,return_index = True, return_counts = True)

(array([  3,   4,   8,  11,  22,  66,  77, 222]),
 array([ 2,  3,  7,  0,  1,  4,  6, 10]),
 array([2, 1, 2, 1, 1, 3, 1, 1]))

## Resize

In [88]:
var2 = np.array([44,1,22,34,5,567,778,44,22,1,34])
np.resize(var2, (3,4))# teen row bn jaye unke andar 4 data aa jaye 


array([[ 44,   1,  22,  34],
       [  5, 567, 778,  44],
       [ 22,   1,  34,  44]])

## Flatten

In [90]:
var2 = np.array([44,1,22,34,5,567,778,44,22,1,34])
y = np.resize(var2, (3,4))
print(y)
print(y.flatten())


[[ 44   1  22  34]
 [  5 567 778  44]
 [ 22   1  34  44]]
[ 44   1  22  34   5 567 778  44  22   1  34  44]


In [95]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2, (3,4))
print(y)
print(y.flatten(order='F'))
print(y.ravel(order='K'))

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
[1 5 3 2 6 4 3 1 5 4 2 6]
[1 2 3 4 5 6 1 2 3 4 5 6]


# Delete and insert in array

In [97]:
var = np.array([5,6,78,9])
print(var.dtype)
np.insert(var,2,10)

int64


array([ 5,  6, 10, 78,  9])

In [98]:
var = np.array([5,6,78,9,6,8,44])
print(var.dtype)
np.insert(var,(2,4),10)

int64


array([ 5,  6, 10, 78,  9, 10,  6,  8, 44])