## Numpy library import 

In [1]:
import numpy as np 

# create Array and convert list in to array

In [15]:
x = [1,2,3,4,5]
y = np.array(x)
print(y)
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print(type(x))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


# take input elements in array and conwert list in to array 

In [16]:
l =[]
for i in range(1,5):
    a = int(input("Enter a number: "))
    l.append(a)

print(np.array(l))

[1 3 4 5]


# check the dimensions of the array using "ndim" function

In [17]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3


# create multidimentional array using "ndmin = dimention of the array"

In [18]:
arr = np.array([1,2,3,5], ndmin = 10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 5]]]]]]]]]]
10


# create numpy array using Numpy Functions
1. Array filled with 0's
2. Array filled with 1's
3. Create an empty array
4. An array with a range of elements 
5. Array diagonal element filled with 1's
6. Create an arrat eith values that are spaced linearly in a specified interval 

## Zeros

In [27]:
import numpy as np
# create numpy array using Numpy Functions
# 1. Array filled with 0's
a = np.zeros(4)
print(a)
print("\n")
b = np.zeros((5,2))
print(b)

[0. 0. 0. 0.]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Ones

In [37]:
arr1 = np.ones(3)
print(arr1)
print("\n")

arr2 = np.ones((4,2,5))
print(arr2)
print(arr2.ndim)

[1. 1. 1.]


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
3


# Empty Array

In [39]:
ar_em = np.empty(4)
print(ar_em)
print("\n")
ar_em2 = np.empty((3,4))
print(ar_em2)

[0. 0. 0. 0.]


[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
 [2.0e-323 2.5e-323 3.0e-323 3.5e-323]]


# Range

In [41]:
range_arr = np.arange(10)
print(range_arr)
print("\n")
range_arr2 = np.arange(1,20,3)
print(range_arr2)


[0 1 2 3 4 5 6 7 8 9]


[ 1  4  7 10 13 16 19]


## diagonal filled with 1

In [48]:
arr_dia = np.eye(3)
print(arr_dia)
print("\n")

arr_dia2 = np.eye(3,3)
print(arr_dia2)
print("\n")

arr_dia2 = np.eye(3,3, k = 1)
print(arr_dia2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# Give a proper space "Linspace"

In [ ]:
arr_lin = np.linspace(1,10, num = 5) # num = 5 means number of elements in a array
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]


## Create array using random numbers 

# Random 

Rand()

In [70]:
var = np.random.rand(5)
print(var)
print("\n")
var2 = np.random.rand(3,4)
print(var2)

[0.68263416 0.80848403 0.3216908  0.2227671  0.68093641]


[[0.94176073 0.88824426 0.50451183 0.36057746]
 [0.70036445 0.71131626 0.5163698  0.63170147]
 [0.2807426  0.60747162 0.96864873 0.48009798]]


Randn()

In [89]:
var3 = np.random.randn(4)
print(var3)
print("\n")
var4 = np.random.randn(3,4) 
print(var4)

[-0.13584783 -0.04019879  0.05402939 -0.32821122]


[[ 0.81839547  0.38526179  0.62575139 -0.78330398]
 [-1.16119713 -0.33987414 -2.15924941 -0.34705087]
 [-0.87847941  0.41720888  0.21355649  0.39316102]]


Ranf()

In [94]:
var_4 = np.random.ranf(4)
print(var_4)
print("\n")
var_5 = np.random.ranf(8)
print(var_5)

[0.13980695 0.02996063 0.39543914 0.36624894]


[0.86008536 0.74960662 0.88406186 0.4771431  0.34374321 0.45478337
 0.41351973 0.6100439 ]


randint()

In [142]:
var6 = np.random.randint(4,10,4)
print(var6)
print("\n")
var7 = np.random.randint(1,100, (3,4,5))
print(var7)
print(var7.ndim)

[5 4 6 8]


[[[95 71 85 82 48]
  [84 56  7 24 99]
  [98 77 22 42 94]
  [46 25 98 18 52]]

 [[55 39  6 91  2]
  [98  3 54 30 31]
  [97 90 42 80 35]
  [63 52 50 95 37]]

 [[45 83 87 77 98]
  [90 47 70  1 67]
  [ 6 32 64 84 19]
  [23 78 88 12 16]]]
3


# Datatype in Numpy Arrays

Check data type

In [147]:
var = np.array([5,6,78,9])
print(var.dtype)
print("\n")
var1 = np.array([5,6,78,9])
print(var1.dtype)
print("\n")
var2 = np.array([5,6,78,9,"a","b","c",7,8,9])
print(var2.dtype)

int64


int64


<U21


Store data from int64 to int8

In [151]:
x = np.array([5,6,7,8], dtype = np.int8)
print(x.dtype)

int8


Convert in to another after changing the dtype value 

In [152]:
x = np.array([5,6,7,8], dtype = "f")
print(x.dtype)

float32


convert the data type of an array in to another datatype using dtype function 

In [155]:
x = np.array([5,6,7,8])
new = np.float32(x)
new_1 = np.int8(new)
print(x.dtype)
print(new.dtype)
print(new_1.dtype)

int64
float32
int8


Directly change the datatype 

Astype function is used to convert the data type of an array into another data type.

In [158]:
new_1 = new.astype(float)
print(new_1)
print(new_1.dtype)

[5. 6. 7. 8.]
float64


# Arthmetic operations in numpy arrays
1. Add
2. Subs
3. mul
4. div
5. mod
6. power
7. reciprocal

In [159]:
a = np.array([1,2,3,4,5])
var_add = a+3
print(var_add)

[4 5 6 7 8]


In [160]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
var = a + b
print(var)

[ 6  8 10 12 14]


Inplace of a+b we use functions to perform arthimetic operations

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.add(a,b)
print(c)
# like that we have substract, multiply, divide, sqrt, etc functions in numpy


[ 6  8 10 12 14]


# Arithmetic Functions

In [5]:
A = np.array([1,4,5,6,73,5,6,7,7,8,8])
print("max",np.max(A))
print("min",np.min(A))   

max 73
min 1


In [7]:
print("maximmum with index value.:",np.max(A),np.argmax(A))
print("minimmum with index value.:",np.min(A),np.argmin(A))

maximmum with index value.: 73 4
minimmum with index value.: 1 0


In [9]:
B = np.array([[1,2,3,4],[5,6,78,7]])
print(B)
print("max:", np.max(B, axis = 0))  # column wise maximum
print("max:", np.max(B, axis = 1))  # row wise maximum

[[ 1  2  3  4]
 [ 5  6 78  7]]
max: [ 5  6 78  7]
max: [ 4 78]


# Shape and Reshaping of an array